index:
    path: /
    controller: App\Controller\SiteController::index

operationsList:
    path: /operationsList
    controller: App\Controller\ApiController::operationsList
    methods: [post]

operationsTotal:
    path: /operationsTotal
    controller: App\Controller\ApiController::operationsTotal
    methods: [post]
